# Generated by Django 3.1 on 2021-04-25 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='associates',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='associates'),
        ),
    ]
