# Generated by Django 3.1 on 2021-04-25 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_associates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='associates',
            new_name='associate',
        ),
    ]
