# Generated by Django 3.1 on 2021-04-25 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_associate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associate',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='associate',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer', to=settings.AUTH_USER_MODEL, verbose_name='peer'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='sender'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Onhold'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Dissociate', 'Dissociate')], default='Waiting', max_length=50, verbose_name='invite status'),
        ),
        migrations.CreateModel(
            name='PeerInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='invite sent')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitee', to=settings.AUTH_USER_MODEL, verbose_name='invitees')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter', to=settings.AUTH_USER_MODEL, verbose_name='inviters')),
            ],
            options={
                'verbose_name': 'PeerInvite',
                'verbose_name_plural': 'PeerInvites',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
