# Generated by Django 3.1 on 2021-04-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210425_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='associate',
            new_name='associates',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='joined_project',
            new_name='joined_projects',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='project',
            new_name='projects',
        ),
        migrations.AddField(
            model_name='associate',
            name='is_connected',
            field=models.BooleanField(default=True, verbose_name='active associate'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Onhold'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Dissociated', 'Dissociated')], default='Waiting', max_length=50, verbose_name='invite status'),
        ),
        migrations.DeleteModel(
            name='PeerInvite',
        ),
    ]
