# Generated by Django 3.1 on 2021-04-25 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0002_auto_20210425_1142'),
        ('user', '0006_auto_20210425_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'managed': True, 'ordering': ['-pk'], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.RenameField(
            model_name='associate',
            old_name='is_connected',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='associate',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='receiver'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='associates',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='associates'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_list', to='project_management.Project', verbose_name='projects'),
        ),
    ]
