# Generated by Django 3.1 on 2021-05-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210425_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='invitation active'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AlterUniqueTogether(
            name='associate',
            unique_together={('sender', 'receiver')},
        ),
    ]
