# Generated by Django 3.1 on 2021-04-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Ongoing Project'), (2, 'Project On-hold'), (3, 'Project Completed'), (4, 'Project Delivered')], default=1, verbose_name='project status')),
                ('project_type', models.PositiveSmallIntegerField(choices=[(2, 'Software Development'), (3, 'Equipment / System Installation')], default=2, verbose_name='project type')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(choices=[(1, 'Project Manager'), (2, 'Project Admin'), (3, 'Project Leader'), (4, 'Member')], default=4)),
                ('permission_1', models.BooleanField(default=False, verbose_name='permission level 1')),
                ('permission_2', models.BooleanField(default=False, verbose_name='permission level 2')),
                ('permission_3', models.BooleanField(default=True, verbose_name='permission level 3')),
            ],
            options={
                'verbose_name': 'ProjectGroup',
                'verbose_name_plural': 'ProjectGroups',
            },
        ),
    ]
